---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xprivatebuckets.panda.io
spec:
  group: panda.io
  names:
    kind: XPrivateBucket
    plural: xprivatebuckets
  claimNames:
    kind: PrivateBucket
    plural: privatebuckets
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            description: |
              The specification for a PrivateBucket Claim.
            properties:
              parameters:
                type: object
                description: |
                  Parameters for configuring this PrivateBucket's Composite Resource(s).
                properties:
                  deletionPolicy:
                    description: Defaults to Delete
                    type: string
                    enum:
                      - Delete
                      - Orphan
                  pandaName:
                    type: string
                    description: |
                      The panda name given to you on the Playground Labs website.
                  region:
                    type: string
                    default: eu-west-2
                  tags:
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - pandaName
              status:
                type: object
                properties:
                  bucketName:
                    type: string
                  bucketArn:
                    type: string
            required:
              - parameters
